-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Monitor principal (WAM OZDSP27IPS, 27" 1440p). Su EDID anuncia 144 Hz a
-- resolución nativa, que es el máximo real del panel.
hl.monitor({
	output = "DP-1",
	mode = "2560x1440@144",
	position = "2560x0",
	scale = 1,
})

-- Panorámica (LG ULTRAWIDE, 2560x1080 por HDMI). El EDID solo ofrece 59.98 y
-- 74.99 Hz a resolución nativa, así que 75 Hz es el tope alcanzable aquí;
-- no existe un modo de 90 Hz. Si el panel admitiera más, sería por DisplayPort.
hl.monitor({
	output = "HDMI-A-1",
	mode = "2560x1080@74.99",
	position = "0x0",
	scale = 1,
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "ghostty"
-- Zen es Firefox por debajo, no Chromium: no entiende --app=, --incognito ni
-- --class. Los binds de abajo usan los equivalentes de Firefox.
local browser = "zen-browser"
local fileManager = "dolphin"
-- Toggle: pkill succeeds (and closes it) when it's open, otherwise it starts.
-- Toggle. Se consultan las instancias vivas en vez de fiarlo al código de
-- salida de "qs kill", que también falla cuando el registro arrastra instancias
-- muertas de sesiones anteriores. Y se selecciona por configuración, no con
-- "pkill -x qs", porque el menú de sesión de la barra es otra instancia de
-- Quickshell y un pkill por nombre se la llevaría por delante.
local menu = "sh -c 'if qs list --all 2>/dev/null | grep -q /launcher/shell.qml; then qs kill -c launcher; else qs -c launcher; fi'"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

-- Repone el loopback del micrófono si quedó encendido en la sesión anterior.
-- Sustituye al autostart de GNOME (~/.config/autostart/loopback-restore.desktop),
-- que Hyprland no lee. El comando `restore` descarga primero cualquier
-- module-loopback huérfano: dos cargados a la vez suenan con eco metálico
-- (comb filtering), que fue el fallo original de este montaje en GNOME.
hl.on("hyprland.start", function()
	hl.exec_cmd(os.getenv("HOME") .. "/.config/waybar/scripts/loopback.sh restore")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 20,

		border_size = 2,

		col = {
			-- Glassmorphism: un solo blanco puro (#ffffff) en todo el borde; lo
			-- que cambia a lo largo del gradiente es el alfa, no el tono. El
			-- borde arranca casi opaco en la esquina superior izquierda y se
			-- desvanece hacia la inferior derecha, que es como el cristal
			-- esmerilado recoge la luz: un filo brillante que se apaga.
			active_border = { colors = { "rgba(ffffffe6)", "rgba(ffffff26)" }, angle = 45 },
			-- La ventana inactiva conserva el filo, pero apenas insinuado.
			inactive_border = "rgba(ffffff1a)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 8,
			passes = 3,
			vibrancy = 0.25,
			noise = 0.02, -- frosted-glass grain
			new_optimizations = true,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

-- Underdamped spring (damping ratio ~0.57): one clear bounce, then it settles
-- instead of oscillating the way stiffness=140/dampening=9 did.
hl.curve("bounce", { type = "spring", mass = 1, stiffness = 170, dampening = 15 })

-- Same idea as "bounce" but barely there: damping ratio ~0.67 overshoots the
-- resting position by about 5% and settles on the first swing back, so a layer
-- coming in gets the launcher's rebound without the visible wobble.
hl.curve("subtleBounce", { type = "spring", mass = 1, stiffness = 200, dampening = 19 })

-- Smooth, monotone exit: no spring, so nothing overshoots on the way out.
hl.curve("easeInOutQuint", { type = "bezier", points = { { 0.83, 0 }, { 0.17, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
-- The style is set per-namespace via layer_rule, since Hyprland only allows a
-- fixed set of animation leaves. Avoid "popin" on layer surfaces: it animates
-- the geometry box from the top-left, so the right/bottom edges visibly step
-- out as squares and the rounded corners get clipped.
-- In: springs past the resting edge and settles back (the subtle rebound).
-- Out: plain easing, so hiding reads as one smooth slide with no rebound at all.
hl.animation({ leaf = "layersIn", enabled = true, speed = 4.2, spring = "subtleBounce" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 3, bezier = "easeInOutQuint" })
-- The fades are timed against the slides above: quick in (the spring is still
-- settling once the bar is fully opaque), and slow enough out that the bar does
-- not blink away before it has finished sliding off.
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 2.5, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Disabled: hyprpaper sets our own wallpaper on start
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "es",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)

-- Loopback del micrófono a los auriculares: escucharte a ti mismo en directo.
-- Es el mismo toggle que el glifo del micro en la barra. L de loopback.
hl.bind(
	mainMod .. " + SHIFT + L",
	hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/waybar/scripts/loopback.sh toggle")
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------------------
---- PORTED FROM set-up/bindings.conf ----
--------------------------------------------

-- Ported from https://github.com/IshimiG/set-up (.config/hypr/bindings.conf),
-- which targets Omarchy. omarchy-launch-* / omarchy-cmd-* helpers don't exist
-- here, so they're replaced with the equivalent plain commands, and the
-- "launch or focus" ones use ~/.local/bin/launch-or-focus (matches an
-- existing window by class/title, or launches the app).

local focusOrLaunch = os.getenv("HOME") .. "/.local/bin/launch-or-focus"

hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + ALT + RETURN", hl.dsp.exec_cmd(terminal .. " -e bash -c \"tmux attach || tmux new -s Work\""))
hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + ALT + B", hl.dsp.exec_cmd(browser .. " --private-window"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + ALT + SHIFT + F", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(focusOrLaunch .. " spotify spotify"))
hl.bind(mainMod .. " + SHIFT + ALT + M", hl.dsp.exec_cmd(focusOrLaunch .. " cliamp " .. terminal .. " --title=cliamp -e cliamp"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd(terminal .. " -e nvim"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd(focusOrLaunch .. " lazydocker " .. terminal .. " --title=lazydocker -e lazydocker"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(focusOrLaunch .. " signal signal-desktop"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd(focusOrLaunch .. " obsidian obsidian"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("typora --enable-wayland-ime"))
hl.bind(mainMod .. " + SHIFT + SLASH", hl.dsp.exec_cmd("1password"))

-- Web apps. Antes se abrían con "chromium --app", que da una ventana sin
-- barra de navegación. Zen es Firefox y no tiene modo app, así que ahora van
-- con --new-window: misma web, pero en una ventana normal con su barra.
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(browser .. ' --new-window https://chatgpt.com'))
hl.bind(mainMod .. " + SHIFT + ALT + A", hl.dsp.exec_cmd(browser .. ' --new-window https://grok.com'))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd(browser .. ' --new-window https://app.hey.com/calendar/weeks/'))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(browser .. ' --new-window https://app.hey.com'))
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd(browser .. ' --new-window https://youtube.com/'))
-- Sin --class: Firefox solo lo respeta en X11, y bajo Wayland el app_id lo
-- fija el .desktop, así que todas las ventanas de Zen comparten clase. El
-- launch-or-focus de estas dos pasa a depender del título de la ventana.
hl.bind(mainMod .. " + SHIFT + ALT + G", hl.dsp.exec_cmd(focusOrLaunch .. ' WhatsApp ' .. browser .. ' --new-window https://web.whatsapp.com/'))
hl.bind(mainMod .. " + SHIFT + CTRL + G", hl.dsp.exec_cmd(focusOrLaunch .. ' "Google Messages" ' .. browser .. ' --new-window https://messages.google.com/web/conversations'))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd(browser .. ' --new-window https://photos.google.com/'))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd(browser .. ' --new-window https://x.com/'))
hl.bind(mainMod .. " + SHIFT + ALT + X", hl.dsp.exec_cmd(browser .. ' --new-window https://x.com/compose/post'))

-- Toggle floating (moved here from SUPER + V)
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))

-- Show/hide waybar. Waybar's own SIGUSR1 hide only sets the GTK window's
-- opacity to 0 and leaves the layer surface mapped, so Hyprland never sees it
-- appear or disappear and cannot animate it. Stopping and restarting the
-- process really destroys and re-creates the surface, which is what makes the
-- layersOut/layersIn animations above run. Waybar maps its surface again about
-- 90ms after launch, so the rebound starts essentially on keypress.
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("sh -c 'pkill -x waybar || waybar'"))

-- SUPER + C centers the window (close is now on SUPER + W above)
hl.bind(mainMod .. " + C", hl.dsp.window.center())

-- Redimensionar la ventana activa con los mismos controles que Omarchy
-- (default/hypr/bindings/tiling.lua): las dos teclas a la derecha del 0.
-- Omarchy las declara por keycode físico, pero el parser Lua de Hyprland
-- 0.56.2 no acepta esa sintaxis (no separa los modificadores de la tecla),
-- así que aquí van por keysym del teclado español:
--   apostrophe = la tecla ' (donde en QWERTY US está el "-")
--   exclamdown = la tecla ¡ (donde en QWERTY US está el "=", antes de Backspace)
-- SUPER solo = 100px, SUPER + ALT = 25px (fino), SUPER + CTRL = 300px (grueso).
-- Sin SHIFT se ajusta el ancho; con SHIFT, el alto.
local resizeSteps = {
	{ mods = "", step = 100 }, -- paso normal
	{ mods = " + ALT", step = 25 }, -- paso fino
	{ mods = " + CTRL", step = 300 }, -- paso grande
}

for _, resize in ipairs(resizeSteps) do
	-- Ancho: ' ensancha hacia la izquierda, ¡ estrecha.
	hl.bind(
		mainMod .. resize.mods .. " + apostrophe",
		hl.dsp.window.resize({ x = -resize.step, y = 0, relative = true }),
		{ repeating = true }
	)
	hl.bind(
		mainMod .. resize.mods .. " + exclamdown",
		hl.dsp.window.resize({ x = resize.step, y = 0, relative = true }),
		{ repeating = true }
	)

	-- Alto: con SHIFT, ' encoge hacia arriba y ¡ estira hacia abajo.
	hl.bind(
		mainMod .. resize.mods .. " + SHIFT + apostrophe",
		hl.dsp.window.resize({ x = 0, y = -resize.step, relative = true }),
		{ repeating = true }
	)
	hl.bind(
		mainMod .. resize.mods .. " + SHIFT + exclamdown",
		hl.dsp.window.resize({ x = 0, y = resize.step, relative = true }),
		{ repeating = true }
	)
end

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Curve/speed come from the global layersIn/layersOut spring above (see
-- "LOOK AND FEEL"); only the per-namespace style differs here, since
-- hl.animation() only accepts Hyprland's fixed set of animation leaves.
hl.layer_rule({
	name = "waybar-anim",
	match = { namespace = "^waybar$" },
	animation = "slide",
})

-- The launcher is a fullscreen transparent Quickshell surface that animates its
-- own card in QML, so the compositor must not animate the surface itself.
-- ignore_alpha keeps the blur on the card (alpha 0.72) and off the dim layer
-- behind it (alpha 0.32).
hl.layer_rule({
	name = "launcher-anim",
	match = { namespace = "^launcher$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- El menú de sesión de la barra es otra superficie Quickshell a pantalla
-- completa (~/.config/quickshell/powermenu/shell.qml) que anima su propia
-- tarjeta, así que el compositor tampoco debe animar la superficie. El
-- ignore_alpha es el mismo del lanzador y por el mismo motivo: mantiene el
-- desenfoque bajo el cristal (alfa 0.74) y lo quita del resto de la superficie,
-- que es transparente y sólo está ahí para recoger los clics de fuera.
hl.layer_rule({
	name = "powermenu-anim",
	match = { namespace = "^powermenu$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- El aviso de paquetes pendientes es un disco centrado que anima su propia
-- entrada, así que el compositor no debe animar la superficie. Mismo
-- ignore_alpha que los otros dos, y por lo mismo: mantiene el desenfoque bajo
-- el cristal del disco.
hl.layer_rule({
	name = "updates-anim",
	match = { namespace = "^updates$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

-----------------------
---- DOTFILES SYNC ----
-----------------------

-- Pulls github.com/IshimiG/set-up on every Hyprland start so the
-- symlinked configs in ~/.config stay in sync with the git repo,
-- then (re)starts waybar with that synced config.
hl.on("hyprland.start", function()
	hl.exec_cmd("~/.local/bin/dotfiles-sync.sh")
	hl.exec_cmd("pkill waybar; waybar")
	hl.exec_cmd("pkill hyprpaper; hyprpaper")
	-- Cuántos paquetes hay pendientes, en un disco en el centro de la
	-- pantalla. El script espera a que haya red antes de contar y no enseña
	-- nada si no hay ninguno, así que puede lanzarse sin más.
	hl.exec_cmd("~/.config/hypr/scripts/updates-notify.sh")
end)

