-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Los monitores son de cada máquina y van en equipo.lua, que se carga al final
-- de este fichero (ver EQUIPO). Aquí no se declara ninguno.

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "ghostty"
-- Zen es Firefox por debajo, no Chromium: no entiende --app=, --incognito ni
-- --class. Los binds de abajo usan los equivalentes de Firefox.
local browser = "zen-browser"
local fileManager = "dolphin"
-- Toggle. El lanzador vive desde el inicio de sesión (ver hyprland.start más
-- abajo) y se abre y se cierra por IPC, como la isla de la barra. Antes era un
-- proceso nuevo en cada pulsación: tardaba ~0,8 s en aparecer y la animación
-- llegaba a medias. Si el proceso no está vivo (se cayó, o se acaba de
-- recargar la config), la llamada falla y se arranca ya abierto.
local menu = "qs -c launcher ipc call launcher toggle >/dev/null 2>&1 || LAUNCHER_ABRIR=1 qs -c launcher -d --no-duplicate"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

-- Repone el loopback del micrófono si quedó encendido en la sesión anterior.
-- Sustituye al autostart de GNOME (~/.config/autostart/loopback-restore.desktop),
-- que Hyprland no lee. El comando `restore` descarga primero cualquier
-- module-loopback huérfano: dos cargados a la vez suenan con eco metálico
-- (comb filtering), que fue el fallo original de este montaje en GNOME.
hl.on("hyprland.start", function()
	hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/loopback.sh restore")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 20,

		border_size = 2,

		col = {
			-- Glassmorphism: un solo blanco puro (#ffffff) en todo el borde; lo
			-- que cambia a lo largo del gradiente es el alfa, no el tono. El
			-- borde arranca casi opaco en la esquina superior izquierda y se
			-- desvanece hacia la inferior derecha, que es como el cristal
			-- esmerilado recoge la luz: un filo brillante que se apaga.
			active_border = { colors = { "rgba(ffffffe6)", "rgba(ffffff26)" }, angle = 45 },
			-- La ventana inactiva conserva el filo, pero apenas insinuado.
			inactive_border = "rgba(ffffff1a)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 8,
			passes = 3,
			vibrancy = 0.25,
			noise = 0.02, -- frosted-glass grain
			new_optimizations = true,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

-- Underdamped spring (damping ratio ~0.57): one clear bounce, then it settles
-- instead of oscillating the way stiffness=140/dampening=9 did.
hl.curve("bounce", { type = "spring", mass = 1, stiffness = 170, dampening = 15 })

-- Same idea as "bounce" but barely there: damping ratio ~0.67 overshoots the
-- resting position by about 5% and settles on the first swing back, so a layer
-- coming in gets the launcher's rebound without the visible wobble.
hl.curve("subtleBounce", { type = "spring", mass = 1, stiffness = 200, dampening = 19 })

-- Smooth, monotone exit: no spring, so nothing overshoots on the way out.
hl.curve("easeInOutQuint", { type = "bezier", points = { { 0.83, 0 }, { 0.17, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
-- The style is set per-namespace via layer_rule, since Hyprland only allows a
-- fixed set of animation leaves. Avoid "popin" on layer surfaces: it animates
-- the geometry box from the top-left, so the right/bottom edges visibly step
-- out as squares and the rounded corners get clipped.
-- In: springs past the resting edge and settles back (the subtle rebound).
-- Out: plain easing, so hiding reads as one smooth slide with no rebound at all.
hl.animation({ leaf = "layersIn", enabled = true, speed = 4.2, spring = "subtleBounce" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 3, bezier = "easeInOutQuint" })
-- The fades are timed against the slides above: quick in (the spring is still
-- settling once the bar is fully opaque), and slow enough out that the bar does
-- not blink away before it has finished sliding off.
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 2.5, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Disabled: hyprpaper sets our own wallpaper on start
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "es",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		-- Desplazamiento natural, clic derecho con dos dedos y el scroll algo
		-- más lento. Sólo lo nota el portátil; en la torre no hay touchpad.
		touchpad = {
			natural_scroll = true,
			clickfinger_behavior = true,
			scroll_factor = 0.4,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only

-- Notificaciones. SUPER+N abre el centro con lo que ya se ha ido de la
-- pantalla; SUPER+ALT+N pone y quita el silencio. No se usa SUPER+SHIFT+N
-- porque bindings.conf ya lo tiene cogido para el editor.
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.config/hypr/scripts/notify-ctl.sh centro"))
hl.bind(mainMod .. " + ALT + N", hl.dsp.exec_cmd("~/.config/hypr/scripts/notify-ctl.sh silencio"))

-- Recordatorio rápido. Mismo interruptor que los demás: si ya está abierta, se
-- cierra, en vez de apilar otra encima.
hl.bind(
	mainMod .. " + R",
	hl.dsp.exec_cmd(
		"sh -c 'if qs list --all 2>/dev/null | grep -q /reminder/shell.qml; then qs kill -c reminder; else qs -c reminder; fi'"
	)
)

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
-- SUPER+SHIFT+S is the screenshot shortcut (below), so sending a window to
-- the scratchpad moved to SUPER+ALT+S.
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Screenshots, like Windows' snipping shortcut: drag a region, click a window
-- or click the desktop for the whole monitor. Copied and saved to
-- ~/Pictures/Screenshots; the notification offers editing it in satty.
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/captura.sh"))
hl.bind("Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/captura.sh"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)

-- Loopback del micrófono a los auriculares: escucharte a ti mismo en directo.
-- Es el mismo toggle que el glifo del micro en la barra. L de loopback.
hl.bind(
	mainMod .. " + SHIFT + L",
	hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/loopback.sh toggle")
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------------------
---- PORTED FROM set-up/bindings.conf ----
--------------------------------------------

-- Ported from the Omarchy bindings.conf this repo started with (it is still
-- in the first commit). omarchy-launch-* / omarchy-cmd-* helpers don't exist
-- here, so they're replaced with the equivalent plain commands, and the
-- "launch or focus" ones use ~/.local/bin/launch-or-focus (in this repo:
-- matches an existing window by class/title, or launches the app).

local focusOrLaunch = os.getenv("HOME") .. "/.local/bin/launch-or-focus"

hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + ALT + RETURN", hl.dsp.exec_cmd(terminal .. " -e bash -c \"tmux attach || tmux new -s Work\""))
hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + ALT + B", hl.dsp.exec_cmd(browser .. " --private-window"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + ALT + SHIFT + F", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(focusOrLaunch .. " spotify spotify"))
hl.bind(mainMod .. " + SHIFT + ALT + M", hl.dsp.exec_cmd(focusOrLaunch .. " cliamp " .. terminal .. " --title=cliamp -e cliamp"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd(terminal .. " -e nvim"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd(focusOrLaunch .. " lazydocker " .. terminal .. " --title=lazydocker -e lazydocker"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(focusOrLaunch .. " signal signal-desktop"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd(focusOrLaunch .. " obsidian obsidian"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("typora --enable-wayland-ime"))
hl.bind(mainMod .. " + SHIFT + SLASH", hl.dsp.exec_cmd("1password"))

-- Web apps. Antes se abrían con "chromium --app", que da una ventana sin
-- barra de navegación. Zen es Firefox y no tiene modo app, así que ahora van
-- con --new-window: misma web, pero en una ventana normal con su barra.
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(browser .. ' --new-window https://chatgpt.com'))
hl.bind(mainMod .. " + SHIFT + ALT + A", hl.dsp.exec_cmd(browser .. ' --new-window https://grok.com'))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd(browser .. ' --new-window https://app.hey.com/calendar/weeks/'))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(browser .. ' --new-window https://app.hey.com'))
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd(browser .. ' --new-window https://youtube.com/'))
-- Sin --class: Firefox solo lo respeta en X11, y bajo Wayland el app_id lo
-- fija el .desktop, así que todas las ventanas de Zen comparten clase. El
-- launch-or-focus de estas dos pasa a depender del título de la ventana.
hl.bind(mainMod .. " + SHIFT + ALT + G", hl.dsp.exec_cmd(focusOrLaunch .. ' WhatsApp ' .. browser .. ' --new-window https://web.whatsapp.com/'))
hl.bind(mainMod .. " + SHIFT + CTRL + G", hl.dsp.exec_cmd(focusOrLaunch .. ' "Google Messages" ' .. browser .. ' --new-window https://messages.google.com/web/conversations'))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd(browser .. ' --new-window https://photos.google.com/'))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd(browser .. ' --new-window https://x.com/'))
hl.bind(mainMod .. " + SHIFT + ALT + X", hl.dsp.exec_cmd(browser .. ' --new-window https://x.com/compose/post'))

-- Toggle floating (moved here from SUPER + V)
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))

-- Esconder y sacar la barra entera. Ya no hay procesos que matar: la barra son
-- cuatro superficies de un mismo Quickshell, y esconderse es una propiedad que
-- anima el cristal hacia arriba. El script sólo se lo pide.
--
-- Cuando la barra era waybar había que matarla y volver a lanzarla para que se
-- animara: su propio SIGUSR1 sólo pone la ventana GTK a opacidad cero y deja la
-- superficie mapeada, así que Hyprland nunca la veía aparecer ni desaparecer y
-- no podía animar nada.
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/barra.sh"))

-- SUPER + C centers the window (close is now on SUPER + W above)
hl.bind(mainMod .. " + C", hl.dsp.window.center())

-- Redimensionar la ventana activa con los mismos controles que Omarchy
-- (default/hypr/bindings/tiling.lua): las dos teclas a la derecha del 0.
-- Omarchy las declara por keycode físico, pero el parser Lua de Hyprland
-- 0.56.2 no acepta esa sintaxis (no separa los modificadores de la tecla),
-- así que aquí van por keysym del teclado español:
--   apostrophe = la tecla ' (donde en QWERTY US está el "-")
--   exclamdown = la tecla ¡ (donde en QWERTY US está el "=", antes de Backspace)
-- SUPER solo = 100px, SUPER + ALT = 25px (fino), SUPER + CTRL = 300px (grueso).
-- Sin SHIFT se ajusta el ancho; con SHIFT, el alto.
local resizeSteps = {
	{ mods = "", step = 100 }, -- paso normal
	{ mods = " + ALT", step = 25 }, -- paso fino
	{ mods = " + CTRL", step = 300 }, -- paso grande
}

for _, resize in ipairs(resizeSteps) do
	-- Ancho: ' ensancha hacia la izquierda, ¡ estrecha.
	hl.bind(
		mainMod .. resize.mods .. " + apostrophe",
		hl.dsp.window.resize({ x = -resize.step, y = 0, relative = true }),
		{ repeating = true }
	)
	hl.bind(
		mainMod .. resize.mods .. " + exclamdown",
		hl.dsp.window.resize({ x = resize.step, y = 0, relative = true }),
		{ repeating = true }
	)

	-- Alto: con SHIFT, ' encoge hacia arriba y ¡ estira hacia abajo.
	hl.bind(
		mainMod .. resize.mods .. " + SHIFT + apostrophe",
		hl.dsp.window.resize({ x = 0, y = -resize.step, relative = true }),
		{ repeating = true }
	)
	hl.bind(
		mainMod .. resize.mods .. " + SHIFT + exclamdown",
		hl.dsp.window.resize({ x = 0, y = resize.step, relative = true }),
		{ repeating = true }
	)
end

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- The launcher is a fullscreen transparent Quickshell surface that animates its
-- own card in QML, so the compositor must not animate the surface itself.
-- ignore_alpha keeps the blur on the card (alpha 0.72) and off the dim layer
-- behind it (alpha 0.32).
hl.layer_rule({
	name = "launcher-anim",
	match = { namespace = "^launcher$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- El aviso de paquetes pendientes es un disco centrado que anima su propia
-- entrada, así que el compositor no debe animar la superficie. Mismo
-- ignore_alpha que los otros dos, y por lo mismo: mantiene el desenfoque bajo
-- el cristal del disco.
hl.layer_rule({
	name = "updates-anim",
	match = { namespace = "^updates$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- La pila de notificaciones. Mismo trato que las demás superficies de
-- Quickshell: cada tarjeta anima su propia entrada, así que el compositor no
-- debe animar la superficie, y el ignore_alpha mantiene el desenfoque bajo el
-- cristal y fuera del hueco transparente que queda entre tarjetas.
hl.layer_rule({
	name = "notifications-anim",
	match = { namespace = "^notifications$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- La ventana de recordatorio rápido, que anima su propia tarjeta.
hl.layer_rule({
	name = "reminder-anim",
	match = { namespace = "^reminder$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- La isla: el bloque central de la barra, que crece hasta convertirse en el
-- panel del calendario, del historial de notificaciones o de la sesión.
--
-- Es una superficie a pantalla completa que no cambia nunca de tamaño; lo que
-- se anima es el Item de dentro, en QML. Por eso no_anim: si el compositor
-- animara también la superficie, la animación de capa se sumaría a la del
-- cristal y el despliegue saldría con dos tiempos.
--
-- El ignore_alpha es el de siempre, y aquí importa especialmente: mantiene el
-- desenfoque bajo el cristal y lo quita de todo lo demás, que es transparente y
-- ni siquiera recibe los clics —la máscara de entrada de la isla los deja pasar
-- al escritorio—.
hl.layer_rule({
	name = "isla-anim",
	match = { namespace = "^isla$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- Los bloques de los lados de la barra (escritorios a la izquierda, telemetría
-- a la derecha). Mismo trato que la isla y por lo mismo: son superficies a
-- pantalla completa que animan su cristal en QML, y pueden desplegar un panel
-- (en el portátil, el de la wifi). Sin esta regla se quedaban sin
-- desenfoque, en negro liso al lado de la isla esmerilada.
hl.layer_rule({
	name = "barra-anim",
	match = { namespace = "^barra$" },
	no_anim = true,
	blur = true,
	ignore_alpha = 0.5,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

-- El btop que abren los módulos de telemetría de la barra: una consulta
-- rápida, no una ventana más del mosaico. Flota en el centro con el tamaño
-- que pide Ghostty (las 80x24 celdas de btop, en TelemetryBlock.qml); por eso
-- no hay size aquí, que va en píxeles y dependería de la letra y la escala.
-- Fijado (pin), te sigue de escritorio en escritorio hasta que lo cierras.
hl.window_rule({
	name = "btop-flotante",
	match = { class = "^ghostty\\.btop$" },

	float = true,
	center = true,
	pin = true,
})

--------------------------------
---- ARRANQUE DEL ESCRITORIO ----
--------------------------------

-- Lo que hace falta en cualquier máquina. Lo propio de cada una (en la torre,
-- el dotfiles-sync.sh que trae el repo al iniciar; en el portátil, polkit e
-- hypridle) arranca desde su equipo.lua.
hl.on("hyprland.start", function()
	hl.exec_cmd("pkill hyprpaper; hyprpaper")
	-- La isla central de la barra, que lleva dentro el daemon de
	-- notificaciones. Va antes que nada de lo que pueda querer notificar: es
	-- quien toma org.freedesktop.Notifications en el bus, y sin él ninguna
	-- aplicación puede avisar de nada.
	--
	-- Antes esto arrancaba "qs -c notifications". El daemon se mudó dentro de
	-- la barra porque el historial tiene que salir del mismo Item que la
	-- campana para poder crecer desde ella, y eso exige el mismo proceso.
	hl.exec_cmd("qs -c bar -d")
	-- El lanzador de SUPER+SPACE, cargado y escondido hasta que se pida.
	hl.exec_cmd("qs -c launcher -d --no-duplicate")
	-- Cuántos paquetes hay pendientes, en una tarjeta colgada del borde de
	-- arriba. El script espera a que haya red antes de contar y no enseña nada
	-- si no hay ninguno, así que puede lanzarse sin más.
	hl.exec_cmd("~/.config/hypr/scripts/updates-notify.sh")
end)


----------------
---- EQUIPO ----
----------------

-- Lo que cambia de una máquina a otra: monitores, dispositivos de entrada y
-- lo que sólo tiene sentido arrancar en una de ellas. Vive en equipo.lua, al
-- lado de este fichero, y sólo existe en la rama de cada máquina
-- (setup/torre, setup/portatil). main, que es la parte común, no lo trae.
--
-- Va al final para que pueda sobrescribir cualquier cosa de lo anterior.
--
-- Se busca antes de cargarlo, en vez de envolver el require en un pcall: así
-- un error dentro de equipo.lua sale en hyprctl configerrors en lugar de
-- quedar tapado como si el fichero no existiera. require lo encuentra junto a
-- este hyprland.lua aunque ~/.config/hypr/hyprland.lua sea un enlace, porque
-- Hyprland arma el package.path desde la carpeta real del fichero, la del repo.
if package.searchpath("equipo", package.path) then
	require("equipo")
else
	-- Sin equipo.lua, cada pantalla arranca en su modo preferido.
	hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end
